// SPDX-License-Identifier: Apache-2.0

//! Extended Stage 9 property, hostile-input, isolation, and boundary campaigns.

use neutral_compiler::{CompilationRequest, CompilationResult, compile, format};
use neutral_core::{
    CancellationToken, SourceContentDigest, StructuralLimits, VocabularyContentDigest,
};
use neutral_encoding::{DecodeLimits, ProducerInfo, decode, encode};
use neutral_probe::summarize;
use neutral_reader::ValidatedDocument;
use neutral_vocabulary::{
    VOCABULARY_ENCODING_VERSION, VOCABULARY_SCHEMA_VERSION, VocabularyLimits, VocabularyLock,
    validate_captured_bundle,
};
use std::{sync::Arc, thread};

/// Frozen minimal source used as the seed for Stage 9 campaigns.
const MINIMAL_SOURCE: &[u8] =
    include_bytes!("../../../../portable/specs/fixtures/positive/syntax/minimal-core.neu");
/// Frozen valid vocabulary bytes used as the vocabulary mutation seed.
const VOCABULARY_BUNDLE: &[u8] = include_bytes!(
    "../../../../portable/specs/fixtures/vocabulary/bundles/positive/comprehensive.json"
);
/// Reproducible seed shared by all stable Stage 9 mutation campaigns.
const STAGE9_FUZZ_SEED: u64 = 0x4e45_5554_5241_4c39;
/// Stable number of cases exercised by each fast campaign.
const STAGE9_FUZZ_CASES: usize = 1_024;
/// Largest arbitrary source or vocabulary input generated by fast campaigns.
const STAGE9_MAX_INPUT_BYTES: usize = 1_024;
/// Producer name used only in test artifact envelopes.
const TEST_PRODUCER: &str = "neutral-stage9-tests";
/// Current package version used in test artifact envelopes.
const TEST_PRODUCER_VERSION: &str = env!("CARGO_PKG_VERSION");
/// Frozen fixture vocabulary identity.
const FIXTURE_VOCABULARY_IDENTITY: &str = "Fixture";
/// Frozen fixture vocabulary release.
const FIXTURE_VOCABULARY_VERSION: &str = "0.1.0";

/// Returns generous deterministic limits for hostile and property campaigns.
fn campaign_limits() -> StructuralLimits {
    StructuralLimits::new(16_384, 16).expect("campaign limits must be nonzero")
}

/// Compiles source and returns authoritative artifacts.
fn successful_artifacts(
    source: &[u8],
    limits: StructuralLimits,
) -> Arc<neutral_ir::CompilationArtifacts> {
    let result = compile(CompilationRequest::new(
        source.to_vec(),
        limits,
        CancellationToken::new(),
    ))
    .expect("valid campaign source must capture");
    let CompilationResult::Success(artifacts) = result else {
        panic!("valid campaign source must compile");
    };
    artifacts
}

/// Asserts that source succeeds under the supplied structural limits.
fn assert_compiles(source: &[u8], limits: StructuralLimits) {
    let result = compile(CompilationRequest::new(
        source.to_vec(),
        limits,
        CancellationToken::new(),
    ))
    .expect("boundary source must remain within the capture limit");
    assert!(matches!(result, CompilationResult::Success(_)));
}

/// Asserts that source fails without authoritative IR under supplied limits.
fn assert_fails_without_ir(source: &[u8], limits: StructuralLimits) {
    let result = compile(CompilationRequest::new(
        source.to_vec(),
        limits,
        CancellationToken::new(),
    ));
    assert!(!matches!(result, Ok(CompilationResult::Success(_))));
}

/// Creates a lock whose digest matches the exact supplied vocabulary bytes.
fn vocabulary_lock(bytes: &[u8]) -> VocabularyLock {
    VocabularyLock::new(
        FIXTURE_VOCABULARY_IDENTITY,
        FIXTURE_VOCABULARY_VERSION,
        VOCABULARY_ENCODING_VERSION,
        VOCABULARY_SCHEMA_VERSION,
        VocabularyContentDigest::from_bytes(bytes),
        Vec::new(),
    )
    .expect("fixture lock constants must remain valid")
}

/// Advances the reproducible xorshift generator used by stable campaigns.
fn fuzz_word(state: &mut u64) -> u64 {
    *state ^= *state << 13;
    *state ^= *state >> 7;
    *state ^= *state << 17;
    *state
}

/// Generates one bounded deterministic arbitrary byte vector.
fn arbitrary_bytes(state: &mut u64) -> Vec<u8> {
    let length = usize::try_from(
        fuzz_word(state) % u64::try_from(STAGE9_MAX_INPUT_BYTES + 1).unwrap_or(u64::MAX),
    )
    .unwrap_or_default();
    (0..length)
        .map(|_| fuzz_word(state).to_le_bytes()[0])
        .collect()
}

#[test]
/// Exercises the complete frozen metamorphic transform set in one composition matrix.
fn property_stage9_complete_metamorphic_composition_matrix() {
    let baseline = successful_artifacts(MINIMAL_SOURCE, campaign_limits());
    let variants = [
        MINIMAL_SOURCE.to_vec(),
        String::from_utf8(MINIMAL_SOURCE.to_vec())
            .expect("fixture source must be UTF-8")
            .replace('\n', "\r\n")
            .into_bytes(),
        [b"// stage9\n".as_slice(), MINIMAL_SOURCE].concat(),
    ];
    for variant in variants {
        let artifacts = successful_artifacts(&variant, campaign_limits());
        assert!(baseline.logically_equivalent(&artifacts));
        let formatted = format(CompilationRequest::new(
            variant,
            campaign_limits(),
            CancellationToken::new(),
        ))
        .expect("valid variant must format");
        let reformatted = format(CompilationRequest::new(
            formatted.as_bytes().to_vec(),
            campaign_limits(),
            CancellationToken::new(),
        ))
        .expect("formatted variant must format again");
        assert_eq!(formatted.as_bytes(), reformatted.as_bytes());
    }
}

#[test]
/// Proves repeated and concurrent adversarial executions retain identical results.
fn property_stage9_adversarial_repeated_and_concurrent_determinism() {
    let inputs = [
        MINIMAL_SOURCE.to_vec(),
        Vec::new(),
        vec![0xff; 257],
        b"neu \"0.1\"\nmodule x\nList<string> values = [\"a\", \"b\"]\n".to_vec(),
    ];
    for input in inputs {
        let expected = compile(CompilationRequest::new(
            input.clone(),
            campaign_limits(),
            CancellationToken::new(),
        ));
        let handles = (0..8)
            .map(|_| {
                let input = input.clone();
                thread::spawn(move || {
                    compile(CompilationRequest::new(
                        input,
                        campaign_limits(),
                        CancellationToken::new(),
                    ))
                })
            })
            .collect::<Vec<_>>();
        for handle in handles {
            assert_eq!(
                handle.join().expect("campaign worker must not panic"),
                expected
            );
        }
    }
}

#[test]
/// Covers every shared structural ceiling exactly at and one unit beyond its boundary.
fn security_stage9_structural_limits_at_and_one_over() {
    let base = campaign_limits();

    let exact_source = MINIMAL_SOURCE.len() as u64;
    assert_compiles(
        MINIMAL_SOURCE,
        StructuralLimits::new(exact_source, 1).expect("exact source limit must be nonzero"),
    );
    assert_fails_without_ir(
        MINIMAL_SOURCE,
        StructuralLimits::new(exact_source - 1, 1).expect("one-under host limit must be nonzero"),
    );

    let cases = [
        (
            b"neu \"0.1\"\nmodule strings\nstring value = \"abcd\"\n".as_slice(),
            base.with_string_bytes(4).expect("string boundary must be valid"),
            base.with_string_bytes(3).expect("string over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule digits\nnum value = 1234\n".as_slice(),
            base.with_numeric_digits(4).expect("digit boundary must be valid"),
            base.with_numeric_digits(3).expect("digit over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule scale\nnum value = 1e-2\n".as_slice(),
            base.with_numeric_scale(2).expect("scale boundary must be valid"),
            base.with_numeric_scale(1).expect("scale over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule declarations\nstring first = \"a\"\nstring second = \"b\"\n".as_slice(),
            base.with_declarations(2).expect("declaration boundary must be valid"),
            base.with_declarations(1).expect("declaration over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule fields\nrecord Item { string first, string second, }\nItem value = { first: \"a\", second: \"b\", }\n".as_slice(),
            base.with_record_fields(2).expect("field boundary must be valid"),
            base.with_record_fields(1).expect("field over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule nesting\nList<string> value = [\"a\"]\n".as_slice(),
            base.with_nesting_depth(1).expect("nesting boundary must be valid"),
            base.with_nesting_depth(1).expect("minimum nesting limit must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule items\nList<string> value = [\"a\", \"b\"]\n".as_slice(),
            base.with_list_items(2).expect("item boundary must be valid"),
            base.with_list_items(1).expect("item over-boundary must be valid"),
        ),
        (
            b"neu \"0.1\"\nmodule traversal\nstring value = \"a\"\n".as_slice(),
            base.with_traversal_nodes(1).expect("traversal boundary must be valid"),
            base.with_traversal_nodes(1).expect("minimum traversal limit must be valid"),
        ),
    ];
    for (source, at, over) in cases {
        assert_compiles(source, at);
        if source
            .windows(b"module nesting".len())
            .any(|part| part == b"module nesting")
        {
            let nested = b"neu \"0.1\"\nmodule nesting\nList<List<string>> value = [[\"a\"]]\n";
            assert_fails_without_ir(nested, over);
        } else if source
            .windows(b"module traversal".len())
            .any(|part| part == b"module traversal")
        {
            let traversed = b"neu \"0.1\"\nmodule traversal\nList<string> value = [\"a\"]\n";
            assert_fails_without_ir(traversed, over);
        } else {
            assert_fails_without_ir(source, over);
        }
    }

    let diagnostic_result = compile(CompilationRequest::new(
        b"neu \"0.1\"\n".to_vec(),
        StructuralLimits::new(64, 1).expect("diagnostic boundary must be valid"),
        CancellationToken::new(),
    ))
    .expect("diagnostic source must capture");
    let CompilationResult::Failure(failure) = diagnostic_result else {
        panic!("invalid source must fail without IR");
    };
    assert_eq!(failure.diagnostics().len(), 1);
}

#[test]
/// Proves separately captured requests cannot reuse stale source identity facts.
fn security_stage9_cross_request_source_fact_isolation() {
    let first = b"neu \"0.1\"\nmodule first\nstring value = \"a\"\n";
    let second = b"neu \"0.1\"\nmodule second\nstring value = \"b\"\n";
    for (source, other) in [
        (first.as_slice(), second.as_slice()),
        (second.as_slice(), first.as_slice()),
    ] {
        let artifacts = successful_artifacts(source, campaign_limits());
        assert_eq!(
            artifacts.source_map().source_digest(),
            SourceContentDigest::from_bytes(source)
        );
        assert_ne!(
            artifacts.source_map().source_digest(),
            SourceContentDigest::from_bytes(other)
        );
    }
}

#[test]
/// Runs the bounded arbitrary source-decoder, lexer, parser, and semantic campaign.
fn fuzz_source_pipeline_campaign_terminates() {
    let mut state = STAGE9_FUZZ_SEED;
    for _ in 0..STAGE9_FUZZ_CASES {
        let bytes = arbitrary_bytes(&mut state);
        let _ = compile(CompilationRequest::new(
            bytes,
            campaign_limits(),
            CancellationToken::new(),
        ));
    }
}

#[test]
/// Runs the bounded arbitrary vocabulary JSON and schema campaign.
fn fuzz_vocabulary_pipeline_campaign_terminates() {
    let mut state = STAGE9_FUZZ_SEED;
    for _ in 0..STAGE9_FUZZ_CASES {
        let bytes = arbitrary_bytes(&mut state);
        let limits = VocabularyLimits::from_structural(campaign_limits());
        let _ = validate_captured_bundle(&bytes, &vocabulary_lock(&bytes), limits);
    }
    assert!(
        validate_captured_bundle(
            VOCABULARY_BUNDLE,
            &vocabulary_lock(VOCABULARY_BUNDLE),
            VocabularyLimits::from_structural(campaign_limits()),
        )
        .is_ok()
    );
}

#[test]
/// Runs the bounded formatted-source campaign and rechecks every accepted result.
fn fuzz_formatter_pipeline_campaign_terminates() {
    let mut state = STAGE9_FUZZ_SEED;
    for _ in 0..STAGE9_FUZZ_CASES {
        let bytes = arbitrary_bytes(&mut state);
        if let Ok(formatted) = format(CompilationRequest::new(
            bytes,
            campaign_limits(),
            CancellationToken::new(),
        )) {
            let second = format(CompilationRequest::new(
                formatted.as_bytes().to_vec(),
                campaign_limits(),
                CancellationToken::new(),
            ))
            .expect("accepted formatter output must remain accepted");
            assert_eq!(formatted.as_bytes(), second.as_bytes());
        }
    }
}

#[test]
/// Runs structured arbitrary mutations through external IR framing and decoding.
fn fuzz_ir_pipeline_campaign_terminates() {
    let artifacts = successful_artifacts(MINIMAL_SOURCE, campaign_limits());
    let reader = ValidatedDocument::from_compiler_output(artifacts)
        .expect("compiler artifacts must satisfy reader invariants");
    let encoded = encode(
        &reader,
        &ProducerInfo::new(TEST_PRODUCER, TEST_PRODUCER_VERSION),
    )
    .expect("valid reader must encode");
    let mut state = STAGE9_FUZZ_SEED;
    for _ in 0..STAGE9_FUZZ_CASES {
        let mut bytes = encoded.as_bytes().to_vec();
        let index = usize::try_from(fuzz_word(&mut state) % bytes.len() as u64).unwrap_or_default();
        bytes[index] ^= fuzz_word(&mut state).to_le_bytes()[0].max(1);
        let _ = decode(&bytes, DecodeLimits::hard(), &CancellationToken::new());
    }
}

#[test]
/// Runs accepted and hostile sources through bounded public probe traversal.
fn fuzz_probe_traversal_campaign_terminates() {
    let mut state = STAGE9_FUZZ_SEED;
    for _ in 0..STAGE9_FUZZ_CASES {
        let mut bytes = MINIMAL_SOURCE.to_vec();
        let index = usize::try_from(fuzz_word(&mut state) % bytes.len() as u64).unwrap_or_default();
        bytes[index] ^= fuzz_word(&mut state).to_le_bytes()[0].max(1);
        if let Ok(CompilationResult::Success(artifacts)) = compile(CompilationRequest::new(
            bytes,
            campaign_limits(),
            CancellationToken::new(),
        )) {
            let reader = ValidatedDocument::from_compiler_output(artifacts)
                .expect("successful compiler output must remain reader-valid");
            let _ = summarize(&reader);
        }
    }
}
