# SPDX-License-Identifier: Apache-2.0

[toolchains]
development = "stable"
release = "stable"
update_policy = "rolling-latest-stable"

[hosts]
supported = ["x86_64-unknown-linux-gnu"]
tested = ["x86_64-unknown-linux-gnu"]
experimental = ["x86_64-pc-windows-msvc"]
unsupported = []
primary_system_test_host = "x86_64-unknown-linux-gnu"

[container]
image = "rust:bookworm"
target = "x86_64-unknown-linux-gnu"
